# Generated by Django 4.1.2 on 2022-11-05 12:30

from django.db import migrations, models

import rmbg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to=rmbg.models.logo_directory_path
                    ),
                ),
            ],
        ),
    ]
