# Generated by Django 4.1.2 on 2022-11-12 23:11

from django.db import migrations, models

import rmbg.models


class Migration(migrations.Migration):

    dependencies = [
        ("rmbg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="nobg",
            field=models.ImageField(
                blank=True, null=True, upload_to=rmbg.models.output_path
            ),
        ),
    ]
